import pandas as pd

# Read the CSV file
df = pd.read_csv('orders.csv')

# Convert order_date to datetime and extract the month and year
df['order_date'] = pd.to_datetime(df['order_date'])
df['year_month'] = df['order_date'].dt.to_period('M')

# Calculate revenue for each order
df['revenue'] = df['product_price'] * df['quantity']

# Compute total revenue generated by the online store for each month
monthly_revenue = df.groupby('year_month')['revenue'].sum()

# Compute total revenue generated by each product
product_revenue = df.groupby('product_name')['revenue'].sum()

# Compute total revenue generated by each customer
customer_revenue = df.groupby('customer_id')['revenue'].sum()

# Identify top 10 customers by revenue
top_customers = customer_revenue.nlargest(10)

# Print results
print(monthly_revenue)
print(product_revenue)
print(top_customers)
